export { PATH_NAME } from "./pathName";
export { NOTI_TYPE_SUCCESS, NOTI_TYPE_WARNING, NOTI_TYPE_DANGER, NOTI_SAVE_SUCCESSFULLY, NOTI_SAVE_FAIL, NOTI_DELETE_SUCCESSFULLY, NOTI_DELETE_FAIL, NOTI_LOGIN_FAIL, NOTI_CONFIRM_DELETE, NOTI_PERMISSION_DENINED, NOTI_CONFIRMED_DELETE } from "./notifyName";
export { URL_SERVER, API_ENDPOINT, FOLDER_IMAGE, USER_LOGIN, ADMIN_FOLDER, TIME_OUT } from "./endPoint";
